# Generated by Django 4.2.6 on 2024-07-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('original_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('offer', models.IntegerField()),
                ('image_path', models.CharField(max_length=355)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
