# Generated by Django 4.2.6 on 2024-07-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myntra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mysavereel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=355)),
            ],
        ),
    ]
